// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcVX0yDUSFWotrV-xRfzQt7bGeCfcKanc',
    appId: '1:294432611545:web:9a1da544c68b28a1d2f2c8',
    messagingSenderId: '294432611545',
    projectId: 'atqn-e8ab8',
    authDomain: 'atqn-e8ab8.firebaseapp.com',
    storageBucket: 'atqn-e8ab8.firebasestorage.app',
    measurementId: 'G-QB685SH9CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9tc1WEte4AHLbid_4ImyTm1Hns03A8KQ',
    appId: '1:294432611545:android:137fcda3850f6731d2f2c8',
    messagingSenderId: '294432611545',
    projectId: 'atqn-e8ab8',
    storageBucket: 'atqn-e8ab8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy22x1KqEdPxE3OdeUpDgynk5TfdhbhbY',
    appId: '1:294432611545:ios:6a995b94c5f9616fd2f2c8',
    messagingSenderId: '294432611545',
    projectId: 'atqn-e8ab8',
    storageBucket: 'atqn-e8ab8.firebasestorage.app',
    iosBundleId: 'com.example.studentProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy22x1KqEdPxE3OdeUpDgynk5TfdhbhbY',
    appId: '1:294432611545:ios:6a995b94c5f9616fd2f2c8',
    messagingSenderId: '294432611545',
    projectId: 'atqn-e8ab8',
    storageBucket: 'atqn-e8ab8.firebasestorage.app',
    iosBundleId: 'com.example.studentProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcVX0yDUSFWotrV-xRfzQt7bGeCfcKanc',
    appId: '1:294432611545:web:78f5791c032cfbb1d2f2c8',
    messagingSenderId: '294432611545',
    projectId: 'atqn-e8ab8',
    authDomain: 'atqn-e8ab8.firebaseapp.com',
    storageBucket: 'atqn-e8ab8.firebasestorage.app',
    measurementId: 'G-0TTMQSK9S6',
  );
}
